apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance" 
  namespace: "openshift-logging"
spec:
  managementState: "Managed"  
  logStore:
    type: "elasticsearch"  
    retentionPolicy: 
      application:
        maxAge: 1d
      infra:
        maxAge: 2d
      audit:
        maxAge: 2d
    elasticsearch:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          effect: "NoSchedule"
      nodeCount: 2 
      storage:
        size: 20G
      resources: 
          limits:
            memory: "16Gi"
          requests:
            memory: "4Gi"
            cpu: "500m"
      proxy: 
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
      redundancyPolicy: "SingleRedundancy"
  visualization:
    type: "kibana"  
    kibana:
      replicas: 1
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          effect: "NoSchedule"        
  collection:
    logs:
      type: "fluentd"  
      fluentd: {}
